// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/proxy.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CreateClientRequest) Validate() error {
	if !(len([]rune(this.DisplayName)) < 20) {
		return github_com_mwitkow_go_proto_validators.FieldError("DisplayName", fmt.Errorf(`max length of display name is 20`))
	}
	return nil
}
func (this *ListClientsRequest) Validate() error {
	return nil
}
func (this *ListClientsResponse) Validate() error {
	for _, item := range this.Clients {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Clients", err)
			}
		}
	}
	return nil
}
func (this *ListBackendServiceUsersRequest) Validate() error {
	return nil
}
func (this *ListBackendServiceUsersResponse) Validate() error {
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
func (this *Client) Validate() error {
	return nil
}
func (this *BackendServiceUser) Validate() error {
	return nil
}
func (this *StartInternalServiceRequest) Validate() error {
	return nil
}
func (this *InternalService) Validate() error {
	return nil
}
