// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/proxy.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateConnectionRequest struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PublicPort           int32    `protobuf:"varint,2,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	InternalPort         int32    `protobuf:"varint,3,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConnectionRequest) Reset()         { *m = CreateConnectionRequest{} }
func (m *CreateConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConnectionRequest) ProtoMessage()    {}
func (*CreateConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{0}
}

func (m *CreateConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConnectionRequest.Unmarshal(m, b)
}
func (m *CreateConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConnectionRequest.Marshal(b, m, deterministic)
}
func (m *CreateConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConnectionRequest.Merge(m, src)
}
func (m *CreateConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConnectionRequest.Size(m)
}
func (m *CreateConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConnectionRequest proto.InternalMessageInfo

func (m *CreateConnectionRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CreateConnectionRequest) GetPublicPort() int32 {
	if m != nil {
		return m.PublicPort
	}
	return 0
}

func (m *CreateConnectionRequest) GetInternalPort() int32 {
	if m != nil {
		return m.InternalPort
	}
	return 0
}

type CreateConnectionResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InternalAddress      string   `protobuf:"bytes,2,opt,name=internal_address,json=internalAddress,proto3" json:"internal_address,omitempty"`
	PublicAddress        string   `protobuf:"bytes,3,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConnectionResponse) Reset()         { *m = CreateConnectionResponse{} }
func (m *CreateConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConnectionResponse) ProtoMessage()    {}
func (*CreateConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{1}
}

func (m *CreateConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConnectionResponse.Unmarshal(m, b)
}
func (m *CreateConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConnectionResponse.Marshal(b, m, deterministic)
}
func (m *CreateConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConnectionResponse.Merge(m, src)
}
func (m *CreateConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConnectionResponse.Size(m)
}
func (m *CreateConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConnectionResponse proto.InternalMessageInfo

func (m *CreateConnectionResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateConnectionResponse) GetInternalAddress() string {
	if m != nil {
		return m.InternalAddress
	}
	return ""
}

func (m *CreateConnectionResponse) GetPublicAddress() string {
	if m != nil {
		return m.PublicAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateConnectionRequest)(nil), "api.CreateConnectionRequest")
	proto.RegisterType((*CreateConnectionResponse)(nil), "api.CreateConnectionResponse")
}

func init() { proto.RegisterFile("proto/proxy.proto", fileDescriptor_58b4a54be18c47e6) }

var fileDescriptor_58b4a54be18c47e6 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x8d, 0x55, 0x61, 0x6f, 0x3f, 0x9c, 0xb9, 0x58, 0x44, 0x71, 0xeb, 0x10, 0xe6, 0xa5,
	0x15, 0xf5, 0x1f, 0xd0, 0xde, 0x45, 0xba, 0x9b, 0x97, 0x91, 0xb6, 0x8f, 0x19, 0x48, 0x93, 0x2c,
	0x49, 0xd5, 0xdd, 0xc4, 0xbf, 0x5c, 0x4c, 0x5b, 0x11, 0xc7, 0x6e, 0x8f, 0x4f, 0x3e, 0xe4, 0x7d,
	0x93, 0x2f, 0x9c, 0x68, 0xa3, 0x9c, 0x4a, 0xb4, 0x51, 0x1f, 0x9b, 0xd8, 0xcf, 0x34, 0x60, 0x9a,
	0x47, 0x5f, 0x04, 0x4e, 0x53, 0x83, 0xcc, 0x61, 0xaa, 0xa4, 0xc4, 0xc2, 0x71, 0x25, 0x33, 0x5c,
	0xd7, 0x68, 0x1d, 0x9d, 0xc2, 0xa0, 0xe4, 0x56, 0x0b, 0xb6, 0x59, 0x4a, 0x56, 0x61, 0x48, 0x26,
	0x64, 0xde, 0xcb, 0xfa, 0x2d, 0x7b, 0x62, 0x15, 0xd2, 0x4b, 0xe8, 0xeb, 0x3a, 0x17, 0xbc, 0x58,
	0x6a, 0x65, 0x5c, 0xb8, 0x3f, 0x21, 0xf3, 0xc3, 0x0c, 0x1a, 0xf4, 0xac, 0x8c, 0xa3, 0x33, 0x18,
	0x72, 0xe9, 0xd0, 0x48, 0x26, 0x1a, 0x25, 0xf0, 0xca, 0xa0, 0x83, 0x3f, 0x52, 0xf4, 0x49, 0x20,
	0xdc, 0x0e, 0x61, 0xb5, 0x92, 0x16, 0x29, 0x85, 0x83, 0x3f, 0xdb, 0xfd, 0x4c, 0xaf, 0x61, 0xfc,
	0x7b, 0x2b, 0x2b, 0x4b, 0x83, 0xd6, 0xfa, 0xdd, 0xbd, 0xec, 0xb8, 0xe3, 0x0f, 0x0d, 0xa6, 0x57,
	0x30, 0x6a, 0x13, 0x76, 0x62, 0xe0, 0xc5, 0x61, 0x43, 0x5b, 0xed, 0x16, 0x61, 0x94, 0x2a, 0xe9,
	0x8c, 0x12, 0x0b, 0x34, 0x6f, 0xbc, 0x40, 0xba, 0x80, 0xf1, 0xff, 0x4c, 0xf4, 0x3c, 0x66, 0x9a,
	0xc7, 0x3b, 0xfe, 0xeb, 0xec, 0x62, 0xc7, 0x69, 0xf3, 0x90, 0x68, 0xef, 0x86, 0x3c, 0xce, 0x5e,
	0xa6, 0x2b, 0xee, 0x5e, 0xeb, 0x3c, 0x2e, 0x54, 0x95, 0xbc, 0x73, 0xb9, 0x12, 0xeb, 0x44, 0xdc,
	0xfb, 0x5a, 0x12, 0x6b, 0x8a, 0x84, 0x69, 0x9e, 0x1f, 0xf9, 0x7e, 0xee, 0xbe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0x45, 0x9b, 0xb8, 0xb4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlServiceClient interface {
	CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (ControlService_CreateConnectionClient, error)
}

type controlServiceClient struct {
	cc *grpc.ClientConn
}

func NewControlServiceClient(cc *grpc.ClientConn) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (ControlService_CreateConnectionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControlService_serviceDesc.Streams[0], "/api.ControlService/CreateConnection", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceCreateConnectionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlService_CreateConnectionClient interface {
	Recv() (*CreateConnectionResponse, error)
	grpc.ClientStream
}

type controlServiceCreateConnectionClient struct {
	grpc.ClientStream
}

func (x *controlServiceCreateConnectionClient) Recv() (*CreateConnectionResponse, error) {
	m := new(CreateConnectionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControlServiceServer is the server API for ControlService service.
type ControlServiceServer interface {
	CreateConnection(*CreateConnectionRequest, ControlService_CreateConnectionServer) error
}

// UnimplementedControlServiceServer can be embedded to have forward compatible implementations.
type UnimplementedControlServiceServer struct {
}

func (*UnimplementedControlServiceServer) CreateConnection(req *CreateConnectionRequest, srv ControlService_CreateConnectionServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateConnection not implemented")
}

func RegisterControlServiceServer(s *grpc.Server, srv ControlServiceServer) {
	s.RegisterService(&_ControlService_serviceDesc, srv)
}

func _ControlService_CreateConnection_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateConnectionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).CreateConnection(m, &controlServiceCreateConnectionServer{stream})
}

type ControlService_CreateConnectionServer interface {
	Send(*CreateConnectionResponse) error
	grpc.ServerStream
}

type controlServiceCreateConnectionServer struct {
	grpc.ServerStream
}

func (x *controlServiceCreateConnectionServer) Send(m *CreateConnectionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateConnection",
			Handler:       _ControlService_CreateConnection_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/proxy.proto",
}
