// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/proxy.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateClientRequest struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	InternalPort         int32    `protobuf:"varint,2,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	PublicPort           int32    `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	SharePublicAddr      bool     `protobuf:"varint,4,opt,name=share_public_addr,json=sharePublicAddr,proto3" json:"share_public_addr,omitempty"`
	Protocol             string   `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BackendPort          int32    `protobuf:"varint,6,opt,name=backend_port,json=backendPort,proto3" json:"backend_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientRequest) Reset()         { *m = CreateClientRequest{} }
func (m *CreateClientRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientRequest) ProtoMessage()    {}
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{0}
}

func (m *CreateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientRequest.Unmarshal(m, b)
}
func (m *CreateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientRequest.Marshal(b, m, deterministic)
}
func (m *CreateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientRequest.Merge(m, src)
}
func (m *CreateClientRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientRequest.Size(m)
}
func (m *CreateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientRequest proto.InternalMessageInfo

func (m *CreateClientRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CreateClientRequest) GetInternalPort() int32 {
	if m != nil {
		return m.InternalPort
	}
	return 0
}

func (m *CreateClientRequest) GetPublicPort() int32 {
	if m != nil {
		return m.PublicPort
	}
	return 0
}

func (m *CreateClientRequest) GetSharePublicAddr() bool {
	if m != nil {
		return m.SharePublicAddr
	}
	return false
}

func (m *CreateClientRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *CreateClientRequest) GetBackendPort() int32 {
	if m != nil {
		return m.BackendPort
	}
	return 0
}

type ListClientsRequest struct {
	PageToken            string   `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListClientsRequest) Reset()         { *m = ListClientsRequest{} }
func (m *ListClientsRequest) String() string { return proto.CompactTextString(m) }
func (*ListClientsRequest) ProtoMessage()    {}
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{1}
}

func (m *ListClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientsRequest.Unmarshal(m, b)
}
func (m *ListClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientsRequest.Marshal(b, m, deterministic)
}
func (m *ListClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientsRequest.Merge(m, src)
}
func (m *ListClientsRequest) XXX_Size() int {
	return xxx_messageInfo_ListClientsRequest.Size(m)
}
func (m *ListClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientsRequest proto.InternalMessageInfo

func (m *ListClientsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListClientsResponse struct {
	Clients              []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	NextPageToken        string    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount           int32     `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListClientsResponse) Reset()         { *m = ListClientsResponse{} }
func (m *ListClientsResponse) String() string { return proto.CompactTextString(m) }
func (*ListClientsResponse) ProtoMessage()    {}
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{2}
}

func (m *ListClientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientsResponse.Unmarshal(m, b)
}
func (m *ListClientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientsResponse.Marshal(b, m, deterministic)
}
func (m *ListClientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientsResponse.Merge(m, src)
}
func (m *ListClientsResponse) XXX_Size() int {
	return xxx_messageInfo_ListClientsResponse.Size(m)
}
func (m *ListClientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientsResponse proto.InternalMessageInfo

func (m *ListClientsResponse) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *ListClientsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListClientsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type ListBackendServiceUsersRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBackendServiceUsersRequest) Reset()         { *m = ListBackendServiceUsersRequest{} }
func (m *ListBackendServiceUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListBackendServiceUsersRequest) ProtoMessage()    {}
func (*ListBackendServiceUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{3}
}

func (m *ListBackendServiceUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackendServiceUsersRequest.Unmarshal(m, b)
}
func (m *ListBackendServiceUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackendServiceUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListBackendServiceUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackendServiceUsersRequest.Merge(m, src)
}
func (m *ListBackendServiceUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListBackendServiceUsersRequest.Size(m)
}
func (m *ListBackendServiceUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackendServiceUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackendServiceUsersRequest proto.InternalMessageInfo

func (m *ListBackendServiceUsersRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListBackendServiceUsersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListBackendServiceUsersResponse struct {
	Users                []*BackendServiceUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPageToken        string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount           int32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListBackendServiceUsersResponse) Reset()         { *m = ListBackendServiceUsersResponse{} }
func (m *ListBackendServiceUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListBackendServiceUsersResponse) ProtoMessage()    {}
func (*ListBackendServiceUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{4}
}

func (m *ListBackendServiceUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackendServiceUsersResponse.Unmarshal(m, b)
}
func (m *ListBackendServiceUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackendServiceUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListBackendServiceUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackendServiceUsersResponse.Merge(m, src)
}
func (m *ListBackendServiceUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListBackendServiceUsersResponse.Size(m)
}
func (m *ListBackendServiceUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackendServiceUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackendServiceUsersResponse proto.InternalMessageInfo

func (m *ListBackendServiceUsersResponse) GetUsers() []*BackendServiceUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListBackendServiceUsersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListBackendServiceUsersResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type Client struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	InternalAddress      string   `protobuf:"bytes,4,opt,name=internal_address,json=internalAddress,proto3" json:"internal_address,omitempty"`
	SharePublicAddr      bool     `protobuf:"varint,5,opt,name=share_public_addr,json=sharePublicAddr,proto3" json:"share_public_addr,omitempty"`
	PublicAddress        string   `protobuf:"bytes,6,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{5}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Client) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Client) GetInternalAddress() string {
	if m != nil {
		return m.InternalAddress
	}
	return ""
}

func (m *Client) GetSharePublicAddr() bool {
	if m != nil {
		return m.SharePublicAddr
	}
	return false
}

func (m *Client) GetPublicAddress() string {
	if m != nil {
		return m.PublicAddress
	}
	return ""
}

type BackendServiceUser struct {
	UserAddr             string   `protobuf:"bytes,1,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	SpeedIn              float64  `protobuf:"fixed64,2,opt,name=speed_in,json=speedIn,proto3" json:"speed_in,omitempty"`
	SpeedOut             float64  `protobuf:"fixed64,3,opt,name=speed_out,json=speedOut,proto3" json:"speed_out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendServiceUser) Reset()         { *m = BackendServiceUser{} }
func (m *BackendServiceUser) String() string { return proto.CompactTextString(m) }
func (*BackendServiceUser) ProtoMessage()    {}
func (*BackendServiceUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{6}
}

func (m *BackendServiceUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendServiceUser.Unmarshal(m, b)
}
func (m *BackendServiceUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendServiceUser.Marshal(b, m, deterministic)
}
func (m *BackendServiceUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendServiceUser.Merge(m, src)
}
func (m *BackendServiceUser) XXX_Size() int {
	return xxx_messageInfo_BackendServiceUser.Size(m)
}
func (m *BackendServiceUser) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendServiceUser.DiscardUnknown(m)
}

var xxx_messageInfo_BackendServiceUser proto.InternalMessageInfo

func (m *BackendServiceUser) GetUserAddr() string {
	if m != nil {
		return m.UserAddr
	}
	return ""
}

func (m *BackendServiceUser) GetSpeedIn() float64 {
	if m != nil {
		return m.SpeedIn
	}
	return 0
}

func (m *BackendServiceUser) GetSpeedOut() float64 {
	if m != nil {
		return m.SpeedOut
	}
	return 0
}

type StartInternalServiceRequest struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	PubPort              int32    `protobuf:"varint,2,opt,name=pub_port,json=pubPort,proto3" json:"pub_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartInternalServiceRequest) Reset()         { *m = StartInternalServiceRequest{} }
func (m *StartInternalServiceRequest) String() string { return proto.CompactTextString(m) }
func (*StartInternalServiceRequest) ProtoMessage()    {}
func (*StartInternalServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{7}
}

func (m *StartInternalServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartInternalServiceRequest.Unmarshal(m, b)
}
func (m *StartInternalServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartInternalServiceRequest.Marshal(b, m, deterministic)
}
func (m *StartInternalServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartInternalServiceRequest.Merge(m, src)
}
func (m *StartInternalServiceRequest) XXX_Size() int {
	return xxx_messageInfo_StartInternalServiceRequest.Size(m)
}
func (m *StartInternalServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartInternalServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartInternalServiceRequest proto.InternalMessageInfo

func (m *StartInternalServiceRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *StartInternalServiceRequest) GetPubPort() int32 {
	if m != nil {
		return m.PubPort
	}
	return 0
}

type ListInternalServiceRequest struct {
	PageToken            string   `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListInternalServiceRequest) Reset()         { *m = ListInternalServiceRequest{} }
func (m *ListInternalServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ListInternalServiceRequest) ProtoMessage()    {}
func (*ListInternalServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{8}
}

func (m *ListInternalServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInternalServiceRequest.Unmarshal(m, b)
}
func (m *ListInternalServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInternalServiceRequest.Marshal(b, m, deterministic)
}
func (m *ListInternalServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInternalServiceRequest.Merge(m, src)
}
func (m *ListInternalServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ListInternalServiceRequest.Size(m)
}
func (m *ListInternalServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInternalServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListInternalServiceRequest proto.InternalMessageInfo

func (m *ListInternalServiceRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListInternalServiceResponse struct {
	Services             []*InternalService `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	NextPageToken        string             `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount           int32              `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListInternalServiceResponse) Reset()         { *m = ListInternalServiceResponse{} }
func (m *ListInternalServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ListInternalServiceResponse) ProtoMessage()    {}
func (*ListInternalServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{9}
}

func (m *ListInternalServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInternalServiceResponse.Unmarshal(m, b)
}
func (m *ListInternalServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInternalServiceResponse.Marshal(b, m, deterministic)
}
func (m *ListInternalServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInternalServiceResponse.Merge(m, src)
}
func (m *ListInternalServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ListInternalServiceResponse.Size(m)
}
func (m *ListInternalServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInternalServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListInternalServiceResponse proto.InternalMessageInfo

func (m *ListInternalServiceResponse) GetServices() []*InternalService {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *ListInternalServiceResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListInternalServiceResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type InternalService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ServiceName          string   `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalService) Reset()         { *m = InternalService{} }
func (m *InternalService) String() string { return proto.CompactTextString(m) }
func (*InternalService) ProtoMessage()    {}
func (*InternalService) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b4a54be18c47e6, []int{10}
}

func (m *InternalService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalService.Unmarshal(m, b)
}
func (m *InternalService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalService.Marshal(b, m, deterministic)
}
func (m *InternalService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalService.Merge(m, src)
}
func (m *InternalService) XXX_Size() int {
	return xxx_messageInfo_InternalService.Size(m)
}
func (m *InternalService) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalService.DiscardUnknown(m)
}

var xxx_messageInfo_InternalService proto.InternalMessageInfo

func (m *InternalService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InternalService) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *InternalService) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateClientRequest)(nil), "api.CreateClientRequest")
	proto.RegisterType((*ListClientsRequest)(nil), "api.ListClientsRequest")
	proto.RegisterType((*ListClientsResponse)(nil), "api.ListClientsResponse")
	proto.RegisterType((*ListBackendServiceUsersRequest)(nil), "api.ListBackendServiceUsersRequest")
	proto.RegisterType((*ListBackendServiceUsersResponse)(nil), "api.ListBackendServiceUsersResponse")
	proto.RegisterType((*Client)(nil), "api.Client")
	proto.RegisterType((*BackendServiceUser)(nil), "api.BackendServiceUser")
	proto.RegisterType((*StartInternalServiceRequest)(nil), "api.StartInternalServiceRequest")
	proto.RegisterType((*ListInternalServiceRequest)(nil), "api.ListInternalServiceRequest")
	proto.RegisterType((*ListInternalServiceResponse)(nil), "api.ListInternalServiceResponse")
	proto.RegisterType((*InternalService)(nil), "api.InternalService")
}

func init() { proto.RegisterFile("proto/proxy.proto", fileDescriptor_58b4a54be18c47e6) }

var fileDescriptor_58b4a54be18c47e6 = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x4e, 0xdb, 0x48,
	0x18, 0xc5, 0x09, 0x09, 0xc9, 0x97, 0x40, 0x96, 0x21, 0x5a, 0x42, 0xd0, 0x6e, 0x8c, 0xb3, 0xac,
	0x02, 0x12, 0x09, 0x82, 0xbd, 0x59, 0xed, 0x15, 0xc9, 0x15, 0x12, 0xda, 0x8d, 0xcc, 0xae, 0x56,
	0xa2, 0x95, 0xa2, 0x89, 0x3d, 0x04, 0x0b, 0xc7, 0x63, 0x66, 0xc6, 0x14, 0x1e, 0xa0, 0x6f, 0xd0,
	0x8b, 0xf6, 0xae, 0x37, 0x7d, 0xa2, 0x3e, 0x40, 0xa5, 0x3e, 0x49, 0x35, 0x33, 0xb6, 0x6b, 0xf2,
	0x43, 0x6f, 0xb8, 0xf3, 0x9c, 0x39, 0xf3, 0x7d, 0x73, 0x4e, 0xce, 0x7c, 0x81, 0xcd, 0x90, 0x51,
	0x41, 0x7b, 0x21, 0xa3, 0x0f, 0x8f, 0x5d, 0xf5, 0x8d, 0xf2, 0x38, 0xf4, 0x9a, 0xed, 0x09, 0x3d,
	0x52, 0xcb, 0xa3, 0x7b, 0xec, 0x7b, 0x2e, 0x16, 0x94, 0xf1, 0x5e, 0xfa, 0xa9, 0x99, 0xd6, 0xbb,
	0x1c, 0x6c, 0x0d, 0x18, 0xc1, 0x82, 0x0c, 0x7c, 0x8f, 0x04, 0xc2, 0x26, 0x77, 0x11, 0xe1, 0x02,
	0x5d, 0x40, 0xd5, 0xf5, 0x78, 0xe8, 0xe3, 0xc7, 0x51, 0x80, 0xa7, 0xa4, 0x61, 0x98, 0x46, 0xa7,
	0xdc, 0x3f, 0xf8, 0xfa, 0xa5, 0xb5, 0x7f, 0x68, 0x4e, 0xf1, 0x83, 0xe9, 0x93, 0x60, 0x22, 0x6e,
	0x4c, 0x7a, 0x6d, 0xc6, 0x3c, 0x53, 0xf2, 0x4c, 0x8f, 0x9b, 0x27, 0xc7, 0x1f, 0x8d, 0xba, 0x5d,
	0x89, 0xe1, 0xbf, 0xf1, 0x94, 0xa0, 0x36, 0xac, 0x7b, 0x81, 0x20, 0x2c, 0xc0, 0xfe, 0x28, 0xa4,
	0x4c, 0x34, 0x72, 0xa6, 0xd1, 0x29, 0xd8, 0xd5, 0x04, 0x1c, 0x52, 0x26, 0x50, 0x0b, 0x2a, 0x61,
	0x34, 0xf6, 0x3d, 0x47, 0x53, 0xf2, 0x8a, 0x02, 0x1a, 0x52, 0x84, 0x43, 0xd8, 0xe4, 0x37, 0x98,
	0x91, 0x51, 0x4c, 0xc3, 0xae, 0xcb, 0x1a, 0xab, 0xa6, 0xd1, 0x29, 0xd9, 0x35, 0xb5, 0x31, 0x54,
	0xf8, 0x99, 0xeb, 0x32, 0xd4, 0x84, 0x92, 0x12, 0xe8, 0x50, 0xbf, 0x51, 0x90, 0x77, 0xb7, 0xd3,
	0x35, 0xda, 0x83, 0xea, 0x18, 0x3b, 0xb7, 0x24, 0x70, 0x75, 0xa7, 0xa2, 0xea, 0x54, 0x89, 0x31,
	0xd9, 0xca, 0x3a, 0x05, 0x74, 0xe1, 0x71, 0xa1, 0x3d, 0xe1, 0x89, 0x29, 0xbf, 0x00, 0x84, 0x78,
	0x42, 0x46, 0x82, 0xde, 0x92, 0x40, 0x5b, 0x62, 0x97, 0x25, 0xf2, 0xaf, 0x04, 0xac, 0xb7, 0x06,
	0x6c, 0x3d, 0x39, 0xc5, 0x43, 0x1a, 0x70, 0x82, 0xf6, 0x61, 0xcd, 0xd1, 0x50, 0xc3, 0x30, 0xf3,
	0x9d, 0xca, 0x49, 0xa5, 0x8b, 0x43, 0xaf, 0x1b, 0x1b, 0x9e, 0xec, 0xa1, 0xdf, 0xa1, 0x16, 0x90,
	0x07, 0x31, 0xca, 0xb4, 0xc8, 0xa9, 0x16, 0xeb, 0x12, 0x1e, 0x26, 0x6d, 0xa4, 0x4f, 0x82, 0x0a,
	0xec, 0x8f, 0x1c, 0x1a, 0x05, 0xa9, 0x4f, 0x0a, 0x1a, 0x48, 0xc4, 0xfa, 0x1f, 0x7e, 0x95, 0xd7,
	0xe8, 0x6b, 0x3d, 0x97, 0x84, 0xdd, 0x7b, 0x0e, 0xf9, 0x8f, 0x13, 0x96, 0x0a, 0xf9, 0x19, 0x8a,
	0x21, 0x66, 0x24, 0x10, 0xb1, 0x88, 0x78, 0x35, 0x23, 0x30, 0x37, 0x2b, 0xf0, 0x83, 0x01, 0xad,
	0xa5, 0x95, 0x63, 0xb1, 0x47, 0x50, 0x88, 0x24, 0x10, 0x4b, 0xdd, 0x56, 0x52, 0xe7, 0x0f, 0xd8,
	0x9a, 0xf5, 0x72, 0xa2, 0x3f, 0x1b, 0x50, 0xd4, 0x8e, 0x22, 0x04, 0xab, 0xdf, 0x33, 0x6b, 0xab,
	0x6f, 0x54, 0x87, 0x42, 0xb6, 0xba, 0x5e, 0xc8, 0x24, 0x3c, 0x49, 0x79, 0x5e, 0x6d, 0x3e, 0x89,
	0xee, 0x01, 0xfc, 0x94, 0x46, 0x57, 0x06, 0x8e, 0x70, 0xae, 0x32, 0x57, 0xb6, 0x6b, 0x09, 0x7e,
	0xa6, 0xe1, 0xc5, 0xf9, 0x2c, 0x2c, 0xce, 0xe7, 0x3e, 0x6c, 0x64, 0x58, 0xb2, 0x68, 0x51, 0xcb,
	0x0e, 0x53, 0x0e, 0xe1, 0xdc, 0xf2, 0x00, 0xcd, 0x7b, 0x87, 0x76, 0xa1, 0x2c, 0xdd, 0xd3, 0x0d,
	0xb4, 0xca, 0x92, 0x04, 0x54, 0xe5, 0x1d, 0x28, 0xf1, 0x90, 0x10, 0x77, 0xe4, 0x69, 0xb1, 0x86,
	0xbd, 0xa6, 0xd6, 0xe7, 0x81, 0x3c, 0xa7, 0xb7, 0x68, 0xa4, 0x2d, 0x34, 0x6c, 0xcd, 0xfd, 0x27,
	0x12, 0xd6, 0x2b, 0xd8, 0xbd, 0x14, 0x98, 0x89, 0xf3, 0x58, 0x55, 0xdc, 0x30, 0x89, 0xcc, 0x1e,
	0x54, 0xb9, 0x46, 0x32, 0x03, 0xc1, 0xae, 0xc4, 0x98, 0xb2, 0x6a, 0x07, 0x4a, 0x61, 0x34, 0xce,
	0x3e, 0xf0, 0xb5, 0x30, 0x1a, 0xab, 0xf7, 0xf4, 0x17, 0x34, 0x65, 0x70, 0x96, 0xd4, 0xfe, 0xc1,
	0xbb, 0x7a, 0x6f, 0xc0, 0xee, 0xc2, 0xd3, 0x71, 0xe4, 0x8e, 0xa1, 0x14, 0x5f, 0x23, 0x49, 0x5d,
	0x5d, 0xa5, 0x6e, 0x96, 0x9f, 0xb2, 0x5e, 0x2e, 0x75, 0xaf, 0xa1, 0x36, 0xd3, 0x65, 0x61, 0xfa,
	0x10, 0xac, 0xaa, 0xdf, 0x4a, 0x37, 0x51, 0xdf, 0x73, 0x86, 0xe6, 0xe7, 0x0c, 0x3d, 0xf9, 0x94,
	0x87, 0x8d, 0x01, 0x0d, 0x04, 0xa3, 0x69, 0xf5, 0x3f, 0xa1, 0x9a, 0x1d, 0xd7, 0xa8, 0xa1, 0x47,
	0xc9, 0xfc, 0x04, 0x6f, 0x66, 0x87, 0x8c, 0xb5, 0x72, 0x6c, 0xa0, 0x3e, 0x54, 0x32, 0xd3, 0x09,
	0xe9, 0x97, 0x39, 0x3f, 0xe5, 0x9a, 0x8d, 0xf9, 0x0d, 0x6d, 0xb4, 0xb5, 0x82, 0xae, 0x61, 0x7b,
	0xc9, 0x00, 0x40, 0xed, 0xf4, 0xd8, 0xf2, 0xc1, 0xd3, 0xfc, 0xed, 0x79, 0x52, 0xda, 0x67, 0x08,
	0xf5, 0x45, 0x61, 0x44, 0xa6, 0x3a, 0xff, 0x4c, 0x4e, 0x9b, 0x0b, 0x7f, 0x7a, 0x6b, 0x05, 0x5d,
	0xe9, 0xd9, 0x3c, 0x5b, 0xb0, 0x95, 0x5e, 0x68, 0x49, 0x3d, 0x73, 0x39, 0x21, 0xb9, 0x6d, 0xbf,
	0x7d, 0xb5, 0x37, 0xf1, 0xc4, 0x4d, 0x34, 0xee, 0x3a, 0x74, 0xda, 0x7b, 0xe3, 0x05, 0x13, 0xff,
	0xae, 0xe7, 0xff, 0xa1, 0xfe, 0x91, 0x7b, 0x9c, 0x39, 0x3d, 0x1c, 0x7a, 0xe3, 0xa2, 0xfa, 0xff,
	0x39, 0xfd, 0x16, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x25, 0xa4, 0x57, 0xaf, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlServiceClient interface {
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (ControlService_CreateClientClient, error)
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
	ListBackendServiceUsers(ctx context.Context, in *ListBackendServiceUsersRequest, opts ...grpc.CallOption) (*ListBackendServiceUsersResponse, error)
	StartInternalService(ctx context.Context, in *StartInternalServiceRequest, opts ...grpc.CallOption) (*InternalService, error)
	ListInternalService(ctx context.Context, in *ListInternalServiceRequest, opts ...grpc.CallOption) (*ListInternalServiceResponse, error)
}

type controlServiceClient struct {
	cc *grpc.ClientConn
}

func NewControlServiceClient(cc *grpc.ClientConn) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (ControlService_CreateClientClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControlService_serviceDesc.Streams[0], "/api.ControlService/CreateClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceCreateClientClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlService_CreateClientClient interface {
	Recv() (*Client, error)
	grpc.ClientStream
}

type controlServiceCreateClientClient struct {
	grpc.ClientStream
}

func (x *controlServiceCreateClientClient) Recv() (*Client, error) {
	m := new(Client)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlServiceClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, "/api.ControlService/ListClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListBackendServiceUsers(ctx context.Context, in *ListBackendServiceUsersRequest, opts ...grpc.CallOption) (*ListBackendServiceUsersResponse, error) {
	out := new(ListBackendServiceUsersResponse)
	err := c.cc.Invoke(ctx, "/api.ControlService/ListBackendServiceUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) StartInternalService(ctx context.Context, in *StartInternalServiceRequest, opts ...grpc.CallOption) (*InternalService, error) {
	out := new(InternalService)
	err := c.cc.Invoke(ctx, "/api.ControlService/StartInternalService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListInternalService(ctx context.Context, in *ListInternalServiceRequest, opts ...grpc.CallOption) (*ListInternalServiceResponse, error) {
	out := new(ListInternalServiceResponse)
	err := c.cc.Invoke(ctx, "/api.ControlService/ListInternalService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
type ControlServiceServer interface {
	CreateClient(*CreateClientRequest, ControlService_CreateClientServer) error
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	ListBackendServiceUsers(context.Context, *ListBackendServiceUsersRequest) (*ListBackendServiceUsersResponse, error)
	StartInternalService(context.Context, *StartInternalServiceRequest) (*InternalService, error)
	ListInternalService(context.Context, *ListInternalServiceRequest) (*ListInternalServiceResponse, error)
}

// UnimplementedControlServiceServer can be embedded to have forward compatible implementations.
type UnimplementedControlServiceServer struct {
}

func (*UnimplementedControlServiceServer) CreateClient(req *CreateClientRequest, srv ControlService_CreateClientServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (*UnimplementedControlServiceServer) ListClients(ctx context.Context, req *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClients not implemented")
}
func (*UnimplementedControlServiceServer) ListBackendServiceUsers(ctx context.Context, req *ListBackendServiceUsersRequest) (*ListBackendServiceUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackendServiceUsers not implemented")
}
func (*UnimplementedControlServiceServer) StartInternalService(ctx context.Context, req *StartInternalServiceRequest) (*InternalService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartInternalService not implemented")
}
func (*UnimplementedControlServiceServer) ListInternalService(ctx context.Context, req *ListInternalServiceRequest) (*ListInternalServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInternalService not implemented")
}

func RegisterControlServiceServer(s *grpc.Server, srv ControlServiceServer) {
	s.RegisterService(&_ControlService_serviceDesc, srv)
}

func _ControlService_CreateClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateClientRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).CreateClient(m, &controlServiceCreateClientServer{stream})
}

type ControlService_CreateClientServer interface {
	Send(*Client) error
	grpc.ServerStream
}

type controlServiceCreateClientServer struct {
	grpc.ServerStream
}

func (x *controlServiceCreateClientServer) Send(m *Client) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ControlService/ListClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListBackendServiceUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackendServiceUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListBackendServiceUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ControlService/ListBackendServiceUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListBackendServiceUsers(ctx, req.(*ListBackendServiceUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_StartInternalService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInternalServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).StartInternalService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ControlService/StartInternalService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).StartInternalService(ctx, req.(*StartInternalServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListInternalService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInternalServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListInternalService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ControlService/ListInternalService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListInternalService(ctx, req.(*ListInternalServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListClients",
			Handler:    _ControlService_ListClients_Handler,
		},
		{
			MethodName: "ListBackendServiceUsers",
			Handler:    _ControlService_ListBackendServiceUsers_Handler,
		},
		{
			MethodName: "StartInternalService",
			Handler:    _ControlService_StartInternalService_Handler,
		},
		{
			MethodName: "ListInternalService",
			Handler:    _ControlService_ListInternalService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateClient",
			Handler:       _ControlService_CreateClient_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/proxy.proto",
}
